[workspace]
members = [
    "neotron-os",
    "utilities/*",
]
resolver = "2"
exclude = [
    "nbuild"
]

[workspace.dependencies]
neotron-sdk = { git = "https://github.com/neotron-compute/neotron-sdk.git", branch = "add-gfx-ioctl-defines" }

[profile.release]
lto = true
debug = true
codegen-units = 1
opt-level = "z"
panic = "abort"

[profile.dev]
panic = "abort"

