name: Build

on: [push, pull_request]

jobs:
  embedded-binaries:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [thumbv6m-none-eabi, thumbv7em-none-eabi, thumbv8m.main-none-eabi]
        start_address: [0x0802_0000, 0x1002_0000]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: rustup target add ${{ matrix.target }}
      - run: rustup component add llvm-tools-preview
      - run: cargo nbuild binary --target=${{ matrix.target }} --start-address=${{ matrix.start_address }}
      - uses: actions/upload-artifact@v4
        if: ${{success()}}
        with:
          name: ${{ matrix.target }}-${{ matrix.start_address }}-binary
          if-no-files-found: error
          path: |
            ./target/${{ matrix.target }}/release/neotron-os
            ./target/${{ matrix.target }}/release/neotron-os.bin
            ./target/${{ matrix.target }}/release/romfs.bin
  x64_64-unknown-linux-gnu-library:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: cargo nbuild library
      - uses: actions/upload-artifact@v4
        if: ${{success()}}
        with:
          name: x64_64-unknown-linux-gnu-library
          if-no-files-found: error
          path: |
            ./target/release/libneotron_os.so
  x86_64-pc-windows-msvc-library:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: cargo nbuild library
      - uses: actions/upload-artifact@v4
        if: ${{success()}}
        with:
          name: x86_64-pc-windows-msvc-library
          if-no-files-found: error
          path: |
            ./target/release/neotron_os.dll
            ./target/release/neotron_os.dll.exp
            ./target/release/neotron_os.dll.lib
            ./target/release/neotron_os.pdb
  aarch64-apple-darwin-library:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: cargo nbuild library
      - uses: actions/upload-artifact@v4
        if: ${{success()}}
        with:
          name: aarch64-apple-darwin-library
          if-no-files-found: error
          path: |
            ./target/release/libneotron_os.dylib
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: cargo nbuild test
  preview-release:
    runs-on: ubuntu-latest
    needs: [embedded-binaries, x64_64-unknown-linux-gnu-library, x86_64-pc-windows-msvc-library, aarch64-apple-darwin-library, run-tests]
    steps:
      - run: mkdir ./release
      - uses: actions/download-artifact@v4
        with:
          path: ./release-${{ github.ref_name }}
      - run: ls -lR ./release-${{ github.ref_name }}
      - run: zip -r ./release-${{ github.ref_name }}.zip ./release-${{ github.ref_name }}
      - uses: actions/upload-artifact@v4
        if: ${{success()}}
        with:
          name: release
          if-no-files-found: error
          path: |
            ./release-${{ github.ref_name }}.zip
  release:
    runs-on: ubuntu-latest
    needs: [preview-release]
    if: github.event_name == 'push' && startswith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: release
          path: .
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            ./release-${{ github.ref_name }}.zip
